// src/components/Footer.tsx
export const Footer = () => {
    return (
        <footer className="w-full h-24 py-2 text-white bg-[#5B7355] text-sm flex flex-col items-center justify-end font-display">
            <div className="">&copy; {new Date().getFullYear()}</div>
            <div className="">All rights reserved, and all that jazz</div>
        </footer>
    );
}

// src/components/Footer.vue
<template>
  <footer class="flex justify-center text-white font-thin">
    <div class="flex-col">
      <p class="text-sm md:text-base">
        All rights reserved, and all that jazz &copy; {{ current_date }}
      </p>
    </div>
  </footer>
</template>

<script>
export default {
  name: "Footer",
  data: () => {
    return {
      current_date: new Date().getFullYear(),
    };
  },
};
</script>
