// src/components/Navbar.vue
<template>
  <nav class="w-full p-6 mb-4">
    <div class="flex justify-center md:justify-between">
      <div class="pt-1 order-first">
        <a href="#top">
          <span
          class="fas fa-code text-hotmag text-5xl block"
          aria-hidden="true"
        ></span>
        </a>
      </div>
      <div class="hidden md:flex md:order-last md:space-x-5 p-4">
        <a href="#projects" class="hover:text-hotmag text-white/80 font-thin"
          >Projects </a>
        <a
          href="https://docs.google.com/document/d/1B2lo_Q2c3jFH3Y4F5X13gHGRFADub1wEtfgeZMF-JK0/edit?usp=drivesdk"
          target="_blank"
          class="hover:text-hotmag text-white/80 font-thin"
          >Resume</a
        >
      </div>
    </div>
  </nav>
</template>

<script scoped>
export default {
  name: "Navbar",
};
</script>

// src/components/Navbar.tsx
export const Navbar = () => {
    return (
        <nav className="bg-[#D9D8D7] flex flex-col md:flex-row md:justify-between md:sticky md:top-0 md:z-10 font-display">
            <div className="text-8xl font-bold text-center mb-5 md:px-5">{'</>'}</div>
            <div className="w-full md:w-1/2 flex md:flex-row justify-around md:items-center">
                <a href="#introduction" className="flex flex-col items-center hover:opacity-70 hover:cursor-pointer">
                    {/* <RocketIcon className='w-7 h-7'></RocketIcon> */}
                    <div className="text-sm">About</div>
                </a>
                <a href="#projects" className="flex flex-col items-center hover:opacity-70 hover:cursor-pointer hover:animate__animated hover:animate__fadeIn">
                    {/* <MixIcon className='w-7 h-7'></MixIcon> */}
                    <div className="text-sm">Projects</div>
                </a>
                <a href="https://docs.google.com/document/d/1B2lo_Q2c3jFH3Y4F5X13gHGRFADub1wEtfgeZMF-JK0/edit?usp=sharing" target="_blank" className="flex flex-col items-center hover:opacity-70 hover:cursor-pointer">
                    {/* <ReaderIcon className='w-7 h-7'></ReaderIcon> */}
                    <div className="text-sm">Resume</div>
                </a>
            </div>
        </nav>
    );
}
