// src/views/Projects.vue
<template>
  <section class="h-fit container mx-auto space-y-11">
    <div class="text-white text-center flex flex-col space-y-4">
      <div class="text-5xl font-bold">
        Previous <span class="text-hotmag">Work</span>
      </div>
      <div class="text-xl">
        Here are some <span class="text-hotmag">projects</span> of mine
      </div>
    </div>
    <div class="flex flex-col md:grid gap-4 md:grid-cols-2 lg:grid-cols-3 mt-3">
      <div v-for="project in projects" :key="project.title">
        <ProjectCard
          :title="project.title"
          :projectDesc="project.projectDesc"
          :projectImage="project.projectImage"
          :tech_stack="project.tech_stack"
          :info="project.info"
        />
      </div>
    </div>
  </section>
</template>

<script>
import ProjectCard from "../components/ProjectCard.vue";
export default {
  name: "Projects",
  components: { ProjectCard },
  data: () => {
    return {
      projects: [
        {
          title: "RateEat",
          projectDesc:
            "A platform that allows users to give and consume item specific reviews and show growth points of businesses.",
          projectImage: "../assets/photo_2022-07-17_20-35-23-modified.png",
          tech_stack: ["Vue", "Nuxt", "Express", "MongoDB"],
          info: {
            product: "Website",
            demo_link: "https://rateeat.app",
            github: false,
          },
        },
        {
          title: "getz Cars",
          projectDesc:
            "A mobile friendly web application that allows users to look for cars according to their preference.",
          projectImage: "Something",
          tech_stack: ["React", "Express", "MongoDB"],
          info: {
            product: "Website",
            demo_link: "https://getzcarsell.com",
            github: false,
          },
        },
        {
          title: "The Joker",
          projectDesc:
            "An android mobile application that fetches users from a thrid party API, and also allows users to post jokes too.",
          projectImage: "Something",
          tech_stack: ["Flutter", "Dart"],
          info: {
            product: "Mobile",
            demo_link: "https://github.com/AtoBrightSide/flutter-jokes-app",
            github: true,
          },
        },
        {
          title: "Lyrics API",
          projectDesc: "A simple API that has ",
          projectImage: "Something",
          tech_stack: ["Python", "Flask"],
          info: {
            product: "Web App",
            demo_link: "https://github.com/AtoBrightSide/lyrics-api",
            github: true,
          },
        },
      ],
    };
  },
};
</script>

// src/components/Projects.tsx
import { ProjectCard, ProjectCardProps } from "./ProjectCard";

export const Projects = () => {
    const PROJECTS: ProjectCardProps[] = [
        {
            title: "RateEat",
            projectDesc: "A platform that allows users to give and consume item specific reviews and show growth points of businesses.",
            projectImage: "/RateEat.png",
            tech_stack: ["Next", "Typescript", "Express", "MongoDB", "Tailwind"],
            product: "Web App",
            demo_link: "https://rateeat.app",
            github: false,
        },
        {
            title: "GetzAuto",
            projectDesc: "A mobile friendly web application that allows users to look for cars according to their preference.",
            projectImage: "/GetzAuto.png",
            tech_stack: ["React", "Typescript", "Tailwind", "Express", "MongoDB"],
            product: "Web App",
            demo_link: "https://getzauto.netlify.app/",
            github: false,
        },
        {
            title: "The Joker",
            projectDesc: "Explore a variety of jokes by type, save your favorites, and get a daily laugh with our fun and easy-to-use joke app.",
            projectImage: "/laptop-gf2aa9359c_1280.png",
            tech_stack: ["Flutter", "Dart",],
            product: "GitHub",
            demo_link: "https://github.com/AtoBrightSide/flutter-jokes-app",
            github: true,
        },
        {
            title: "Lyrics API",
            projectDesc: "The lyrics API allows music lovers to explore, upload, and like song lyrics, with full CRUD functionality and user registration ",
            projectImage: "/laptop-gf2aa9359c_1280.png",
            tech_stack: ["Python", "Flask", "Postgres"],
            product: "GitHub",
            demo_link: "https://github.com/AtoBrightSide/lyrics-api",
            github: true,
        },
        {
            title: "EveryoneShops",
            projectDesc: "EveryoneShops is a versatile e-commerce website template built with TypeScript and React. Designed to be a flexible solution, it can be adapted to suit the needs of any business looking to establish an online presence. Whether you're selling electronics, fashion, groceries, or anything else, EveryoneShops provides a solid foundation to get started quickly and efficiently.",
            projectImage: "/EveryoneShops_1.png",
            tech_stack: ["Typescript", "React", "Tailwind"],
            product: "Web App",
            demo_link: "https://everyoneshops.netlify.app",
            github: false,
        },
    ];
    return (
        <div id="projects" className="w-full flex flex-col md:flex md:flex-row md:flex-wrap items-center mt-10 md:px-10 gap-y-5">
            <div className="text-3xl md:text-6xl w-full text-center">Previous<span className="font-bold">Work</span></div>
            {PROJECTS.map((project, index) => <ProjectCard key={index} project={project} />)}
        </div>
    );
}
